language: php
php:
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - phpunit -c phpunit.dist.xml --testsuite unit --coverage-clover coverage.clover
  - phpunit -c phpunit.dist.xml --testsuite integration

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
